include = ["**/*.toml"]
exclude = []

[formatting]
# === Alignment and Spacing ===
align_entries = true
align_comments = true
compact_entries = false

# === Arrays and Inline Tables ===
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = false
compact_inline_tables = false
inline_table_expand = true

# === Indentation and Structure ===
indent_entries = false
indent_tables = false
indent_string = "  "
column_width = 120

# === Ordering and Stability ===
reorder_keys = false
reorder_arrays = false
reorder_inline_tables = false

# === Whitespace and Newlines ===
trailing_newline = true
allowed_blank_lines = 1
crlf = false

[schema]
enabled = true
path = "taplo://taplo.toml"
